### ISSUE TITLE
Thanksgiving schedule??

### ISSUE THREAD

**Issue by znmeb** [hackoregon/hack-university-data-science#10]
The README.md says "no class November 22-24 for Thanksgiving break" but further down you have K-means clustering and principal component analysis on those days.

**Comment by Heidi-** [comment]
I wasn't _really_ planning on covering those topics! ;)

Just kidding...sharp eyes, Ed. Schedule has been updated.

**Comment by znmeb** [comment]
I was also impressed that a Hack Oregon project might use principal component analysis ;-)
